Tone down syntax highlighting of recognized identifiers
modelica/ModelicaSpecification pull request #2690
Opened 2020-10-14 21:27 UTC by henrikt-ma

The current color of the "keyword" group (let's call the members the _recognized identifiers_) including things like `connect`, `der` and `Real` (but not the true keywords such as `if`, `parameter` and `terminate`) is a very bright red that makes these words really pop out of the text.  This PR wants to address this by using a more toned down color instead.

To start with, the proposed solution is just to change the bright red to brown, but we should probably also discuss the other (true) keyword color, and make sure that the colors we choose go well together.

2020-10-15 05:32 UTC, henrikt-ma commented
Now marked as _Draft_ to reflect that I think it is better that we collect feedback and play around with different ideas for a while to let this settle.

2020-10-21 19:27 UTC, henrikt-ma commented
Removing _Draft_ state, as there seem to be no interest in discussing this further.

I don't think we need to make a big fuss about this; if we can agree that it is an improvement over what we had before, it should be possible to accept and rest assured that changing it again in the future isn't going to be a problem.

2020-10-26 12:52 UTC, HansOlsson commented
> To start with, the proposed solution is just to change the bright red to brown, but we should probably also discuss the other (true) keyword color, and make sure that the colors we choose go well together.

This sounds like a very good improvement, and I have also noticed this problem. (Currently scheduling items before reviewing them in detail.)

2020-11-06 12:10 UTC, HansOlsson reviewed
Will look through it in more detail later, in general it is good - but to me comments are a bit hard to read with the new color. I prefer a darker green for that reason.

2020-11-06 12:36 UTC, HansOlsson requested changes
Looks good, except that as indicated I find the green a bit hard to read.

2020-11-06 21:43 UTC, henrikt-ma commented
> Looks good, except that as indicated I find the green a bit hard to read.

I can see what you mean.  Better now?

2020-11-09 09:21 UTC, HansOlsson requested changes
All is now good, except for the grayed out semicolon.
I see two problems:

- I generally find it a bit distracting. Basically I find it easier to ignore the more visible semi-colon than to ignore its absence.
- When used inside matrices it becomes confusing, see: "10.4.2.1 Array Concatenation along First and Second Dimensions". The reason is that in a matrix it's would make more sense to replace the comma (not semi-colon) by white-space, e.g. `[1 2;3 4]`. Thus if I see something looking like `[1 2]` I assume it is `[1,2]` not `[1;2]`

2020-11-09 09:52 UTC, henrikt-ma commented
> All is now good, except for the grayed out semicolon.
> I see two problems:
> 
> * I generally find it a bit distracting. Basically I find it easier to ignore the more visible semi-colon than to ignore its absence.
> * When used inside matrices it becomes confusing, see: "10.4.2.1 Array Concatenation along First and Second Dimensions". The reason is that in a matrix it's would make more sense to replace the comma (not semi-colon) by white-space, e.g. `[1 2;3 4]`. Thus if I see something looking like `[1 2]` I assume it is `[1,2]` not `[1;2]`

Fixed.

2020-11-09 09:54 UTC, HansOlsson approved these changes
Looks good now.

2020-11-09 10:03 UTC, merged