Better integration of terms 'instantaneous equation/statement'
modelica/ModelicaSpecification pull request #2788
Opened 2020-12-28 22:52 UTC by henrikt-ma

This addresses another comment left behind when introducing the document index.

Since the terms _instantaneous_, _instantaneous equation_, and _instantaneous statement_ are only used in the introductory chapter, one alternative seems to be to not have them introduced at all.  On the other hand, the idea of having these concepts defined isn't strange to me, so I'm just bringing this up as a possibility rather than actually suggesting to remove them.

2020-12-29 15:09 UTC, HansOlsson commented
> This addresses another comment left behind when introducing the document index.
> 
> Since the terms _instantaneous_, _instantaneous equation_, and _instantaneous statement_ are only used in the introductory chapter, one alternative seems to be to not have them introduced at all. On the other hand, the idea of having these concepts defined isn't strange to me, so I'm just bringing this up as a possibility rather than actually suggesting to remove them.

I think I believe I would prefer to not define it. The reason is that we define when-equations in terms of a rewriting them to if-equations; which means that after rewriting they are not instantaneous equations. They are still not "continuous" as they are held constant between events, but I don't know the best term to describe them.

2020-12-29 23:14 UTC, henrikt-ma commented
> I think I believe I would prefer to not define it. The reason is that we define when-equations in terms of a rewriting them to if-equations; which means that after rewriting they are not instantaneous equations. They are still not "continuous" as they are held constant between events, but I don't know the best term to describe them.

If we're not even sure which way to go with this, it doesn't sound like any change is going to make it into the release, but that's fine.  The ball has been set rolling, and if we find a resolution that can make it into the release, that's just a bonus.

While there may be good reasons for throwing out anything _instantaneous_ from the specification, I don't think the current rewriting of when-equations into if-equations is a valid one, as this is only some sort of conceptual thing.  If it really is more than that to you, then I think this is something we should try to describe more rigorously.  On the other hand, if that's something we would really be planning to investigate (I imagine it being a rather tough thing to settle), I'd consider that plan reason enough to throw out _instantaneous_ already now, as it currently doesn't do much good.

I guess your suggestion includes rewriting the introductory chapter so that _instantaneous_ isn't mentioned?

2020-12-31 17:31 UTC, HansOlsson commented
> I guess your suggestion includes rewriting the introductory chapter so that _instantaneous_ isn't mentioned?

Yes. I realized that for when-statements it is even messier; as they can be part of an algorithm - together with normal equations. To say that _part_ of an algorithm is _instantaneous_ sounds odd to me. I think that another word that indicates that even if valid all the time (due to rewriting) they are only "activated" "changing" (or something like that) at certain time points.
(And then there are synchronous equations as well.)

2021-01-08 22:52 UTC, henrikt-ma commented
> > I guess your suggestion includes rewriting the introductory chapter so that _instantaneous_ isn't mentioned?
> 
> Yes. I realized that for when-statements it is even messier; as they can be part of an algorithm - together with normal equations. To say that _part_ of an algorithm is _instantaneous_ sounds odd to me. I think that another word that indicates that even if valid all the time (due to rewriting) they are only "activated" "changing" (or something like that) at certain time points.
> (And then there are synchronous equations as well.)

Done.  Given that this has become more drastic than originally planned, I'll try to get attention from more reviewers.

2021-01-11 07:24 UTC, gkurzbach approved these changes
looks good.

2021-01-11 15:12 UTC, eshmoylova requested changes

2021-01-11 20:56 UTC, henrikt-ma commented on chapters/equations.tex
> -Special cases are: initial equations, instantaneous equations, declaration equations.
No, at least it was not the intention that it should be read as exceptions to the previous rule.  The sentence was simply added to the paragraph in the most simple way when being transferred from the old glossary into the main part of the document.

2021-01-12 14:30 UTC, eshmoylova commented on chapters/equations.tex
> -Special cases are: initial equations, instantaneous equations, declaration equations.
OK, but then is the previous sentence on line 6 accurate? The when-equations define for which variables they need to be solved don't they? I realize it is not part of your change really. Should I open a ticket about it? Except without your change the sentence on line 8 still can be interpreted the way I thought it was and then there is no issue.

2021-01-12 15:51 UTC, henrikt-ma commented on chapters/equations.tex
> -Special cases are: initial equations, instantaneous equations, declaration equations.
Yes, please open a new issue.  I think the previous statement is wrong also regarding statements; you can't assume that an algorithm will be solved with respect to its output variables.

2021-01-14 14:22 UTC, eshmoylova approved these changes

2021-01-14 14:41 UTC, eshmoylova commented on chapters/equations.tex
> -Special cases are: initial equations, instantaneous equations, declaration equations.
Created #2814.

2021-01-25 16:17 UTC, HansOlsson approved these changes
Ok

2021-01-25 16:17 UTC, merged