Remove HTML footer links to bibliography and index
modelica/ModelicaSpecification pull request #2832
Opened 2021-01-26 07:21 UTC by henrikt-ma

Addresses one of the items in #2825:
> - [ ] The footer is missing white space between links (looks like: HeadingReferencesIndex)

While I think it is good for the page layout to have a footer, I don't consider any of the links to be of importance.  Hence, rather than trying to improve the styling of the links, I found it better to simply remove them.  The only reason I see for keeping the links to the previous and next chapter is that we don't have much else for populating the footer (except for the LaTeXML build timestamp, which I think is a nice way to give credit to the LaTeXML project on which we rely so heavily).

@HansOlsson: This is another PR where it would be good to have a documented procedure for also targeting the current maintenance branch.

2021-01-26 09:58 UTC, HansOlsson commented
I can understand that the bibliography isn't that generally useful (as there are links from each specific item), but the index should be more generally useful.

And as far as I can see 
` padding-left: 0.5em;`
fixes the styling.

2021-01-26 13:44 UTC, henrikt-ma commented
> I can understand that the bibliography isn't that generally useful (as there are links from each specific item), but the index should be more generally useful.

Yes, a link to the index is generally a very useful thing, but not hidden at the bottom of the page.  Currently, it's always (up to LaTeXML bugs) within arms reach in the table of contents.  To be meaningful in the footer, I think the footer would have to use a fixed position, but in my opinion that would be a waste of space on small screens.

2021-02-04 08:54 UTC, HansOlsson requested changes
To me just adding the space as suggested seems nicer (at least for index).

2021-02-04 13:42 UTC, henrikt-ma commented
> To me just adding the space as suggested seems nicer (at least for index).

OK, if you really want the link to the index, I'll make an attempt to put it in a fixed position at the top, where it would be much more useful.

2021-02-19 08:22 UTC, HansOlsson approved these changes
Ok, looks good and new image is in public domain.

2021-02-19 08:22 UTC, merged