Add restriction on inverse and derivative
modelica/ModelicaSpecification pull request #2863
Opened 2021-02-19 09:26 UTC by HansOlsson

Closes #2837

2021-02-19 16:35 UTC, eshmoylova requested changes

2021-02-19 16:35 UTC, eshmoylova commented on chapters/functions.tex
> +This requires that for all valid values of the input arguments of \lstinline!$f_2$($\ldots$, y, $\ldots$)! and $u_k$ being calculated as \lstinline!$u_k$ := $f_2$($\ldots$, y, $\ldots$)! implies
I find this sentence very hard to parse. Maybe:
```suggestion
This requires that $f_2$ is such that, if $u_k$ is calculated as \lstinline!$u_k$ := $f_2$($\ldots$, y, $\ldots$)!, the equality \lstinline!y = $f_1$($\ldots$, $u_k$, $\ldots$)! is satisfied up to a certain precision, for all valid values of the input arguments of \lstinline!$f_2$($\ldots$, y, $\ldots$)!.
```

2021-02-19 16:39 UTC, HansOlsson commented on chapters/functions.tex
> +Note that in practive tools may over-optimize this.
Thanks for catching this.

2021-02-19 16:42 UTC, HansOlsson commented on chapters/functions.tex
> +\begin{nonnormative}
Hmm... I'm not sure, and I think nonnormative makes sense here. We should likely develop better guidelines.

To me example is for general examples, whereas the nonnormative text is more about explanations - and the main part of this is that it explains what a derivative means.

2021-02-19 16:55 UTC, eshmoylova approved these changes
Looks good to me.

2021-02-19 16:58 UTC, eshmoylova commented on chapters/functions.tex
> +\begin{nonnormative}
OK, I agree that nonnormative makes more sense here.

2021-02-19 17:07 UTC, merged

2021-03-01 21:38 UTC, henrikt-ma reviewed
Adding a comment after the fact of merging, and will create separate PR for further discussion.

2021-03-01 21:38 UTC, henrikt-ma commented on chapters/functions.tex
> +Note that in practice tools may over-optimize this.
To say _over-optimize_ sounds a little like the tools would be doing it wrong.  I'd rather say this:
> Note that tools are not required to use the provided derivative, and might solve the equations completely without numeric integration.