Optional semi
modelica/ModelicaSpecification pull request #2870
Opened 2021-02-23 14:47 UTC by HansOlsson

Closes #2801

2021-02-23 16:12 UTC, eshmoylova requested changes
Should there also be semicolon in the paragraphs's headings. For example, on line 1691 (unmodified version):
```
\paragraph*{convertClass("OldClass", "NewClass")}\label{convertclassoldclassnewclass}\annotationindex{convertClass}
```
Should it be:
```
\paragraph*{convertClass("OldClass", "NewClass");}\label{convertclassoldclassnewclass}\annotationindex{convertClass}
```
(Since these lines have not changed it does not allow me to comment inline.)
There are semi-colons in the convertMessage paragraphs on lines 1870 and 1880 (unmodified version).

2021-02-23 16:12 UTC, eshmoylova commented on chapters/annotations.tex
>               "Modelica.Thermal.FluidHeatFlow.Components.Pipe")
One more case here (unless we want to show that they are optional)
```suggestion
             "Modelica.Thermal.FluidHeatFlow.Components.Pipe");
```

2021-02-23 16:12 UTC, eshmoylova commented on chapters/annotations.tex
>               "Modelica.Blocks.Interaction.Show.RealValue")
Here as well.
```suggestion
             "Modelica.Blocks.Interaction.Show.RealValue");
```

2021-02-23 16:12 UTC, eshmoylova commented on chapters/annotations.tex
>     "Modelica.Electrical.Machines.BasicMachines.QuasiStaticDCMachines")
And here.
```suggestion
   "Modelica.Electrical.Machines.BasicMachines.QuasiStaticDCMachines");
```

2021-02-25 10:14 UTC, HansOlsson commented
> Should there also be semicolon in the paragraphs's headings. 

My preference is for not having them, similarly as you don't use a period at the end of a heading.

> There are semi-colons in the convertMessage paragraphs on lines 1870 and 1880 (unmodified version).

Ok, they should be changed then to be consistent.

2021-02-25 10:45 UTC, gkurzbach approved these changes
With the changes requested by Elena I agree to the changes.

2021-02-25 15:11 UTC, eshmoylova commented
> > Should there also be semicolon in the paragraphs's headings.
> 
> My preference is for not having them, similarly as you don't use a period at the end of a heading.
> 
> > There are semi-colons in the convertMessage paragraphs on lines 1870 and 1880 (unmodified version).
> 
> Ok, they should then be changed to be consistent.

I would be OK with removing them from convertMessage.

2021-02-25 15:22 UTC, HansOlsson commented
> > > Should there also be semicolon in the paragraphs's headings.
> > 
> > 
> > My preference is for not having them, similarly as you don't use a period at the end of a heading.
> > > There are semi-colons in the convertMessage paragraphs on lines 1870 and 1880 (unmodified version).
> > 
> > 
> > Ok, they should then be changed to be consistent.
> 
> I would be OK with removing them from convertMessage.

That is now done.

2021-02-25 15:30 UTC, eshmoylova approved these changes
Looks good.

2021-02-25 15:31 UTC, merged