ClarifyPureAsDiscussed
modelica/ModelicaSpecification pull request #3066
Opened 2021-12-08 13:29 UTC by HansOlsson

Closes #2971

2021-12-09 15:42 UTC, henrikt-ma commented on chapters/functions.tex
>    \lstinline!pure(impureFunctionCall($\ldots$))! -- which allows calling impure functions in any pure context.
The name of the callee shouldn't be `impureFunctionCall`:
```suggestion
  \lstinline!pure(impureFunction($\ldots$))! -- which allows calling impure functions in any pure context.
```

2021-12-09 15:52 UTC, henrikt-ma requested changes
With a more direct formulation this looks OK to me, but lacking a really clear conclusion in #2971 it would be good to also get an approval from @jonathankampemodelon.

Edit: At least some kind of positive feed-back from @jonathankampemodelon, as he can't be added as reviewer.

2021-12-09 15:52 UTC, henrikt-ma commented on chapters/functions.tex
> +  Note that the argument to \lstinline!pure! must be a function call, it only applies to the call and not to the arguments of the function call.
This is more than just a note:
```suggestion
  The wrapping in \lstinline!pure($\ldots$)! only by-passes the purity checking of the callee \lstinline!impureFunction!; the argument expressions of the function call are not affected.
```

2021-12-10 10:50 UTC, henrikt-ma reviewed
I am OK with the way this is written, but it would be good to "also" get an approval from someone else before merging.

2021-12-10 10:51 UTC, henrikt-ma approved these changes

2021-12-10 12:44 UTC, sjoelund approved these changes
Seems OK. I tried it in OpenModelica, but apparently we don't even parse `pure` as a function call so this is not used by any library I know of and would not cause problems either way it is clarified...

2021-12-16 14:41 UTC, merged