Cleanup triggered by clumsy logic in Modelica code
modelica/ModelicaSpecification pull request #3092
Opened 2022-01-18 16:18 UTC by henrikt-ma

Fixes #3080.

Similar `if`-expressions were also found in some other chapters, so these were also fixed.

Please see individual commits to separate conversion to sentence-based line breaks from actual changes.

2022-01-19 21:42 UTC, HansOlsson reviewed
Looks, good - but the name of the PR is misleading.

2022-01-20 09:01 UTC, HansOlsson requested changes
Rename the PR to something more generic and we are good to go.

2022-01-21 10:26 UTC, henrikt-ma commented
> Rename the PR to something more generic and we are good to go.

Will that do?

2022-01-23 20:33 UTC, HansOlsson approved these changes
Ok

2022-01-23 20:33 UTC, merged