Variability rule for multiple return assignment
modelica/ModelicaSpecification pull request #3135
Opened 2022-03-18 08:09 UTC by henrikt-ma

This is a pretty obvious generalization of the variability rule for single variable assignments.

As far as I can tell, we don't need anything extra for the case of multiple return equations.

2022-03-18 08:55 UTC, perost approved these changes

2022-03-18 09:11 UTC, HansOlsson requested changes
I find that items in the list should be re-ordered; as the multi-returning seems out of place - especially as it is a much rarer case than parameter-bindings.

I'm unsure exactly how, but perhaps:
- Bindings
- Parameter-binding
- Discrete-time
- Perfect matching of equations
- Assignments
- Multiple return assignment

2022-03-18 11:30 UTC, henrikt-ma commented
OK, let's try to clean up a bit while we're at it.  What's the point of having this item at all in the list?
>\item
>  If \lstinline!v! is a discrete-time component then \lstinline!expr! needs to be a discrete-time expression.

Similarly, shouldn't this item be simplified to only concern base type attributes, as there already is a general item about binding equations?
> \item
>  The right-hand side expression in a binding equation (that is, \lstinline!expr!) of a parameter component and of the base type attributes (such as \lstinline!start!) needs to be a parameter or constant expression.

2022-03-18 11:32 UTC, henrikt-ma commented
> I find that items in the list should be re-ordered; as the multi-returning seems out of place - especially as it is a much rarer case than parameter-bindings.

Yes, it's rare.  The point of placing it below the item for "normal" assignments is that the two are so closely related.

2022-03-18 11:33 UTC, eshmoylova commented
I was going to say the same as @henrikt-ma.

2022-03-18 11:44 UTC, perost commented
> Similarly, shouldn't this item be simplified to only concern base type attributes, as there already is a general item about binding equations?
> 
> > \item
> > The right-hand side expression in a binding equation (that is, \lstinline!expr!) of a parameter component and of the base type attributes (such as \lstinline!start!) needs to be a parameter or constant expression.

Technically we don't even really need an item specifically for the base type attributes, since they're declared as parameters in [4.8](https://specification.modelica.org/master/class-predefined-types-and-declarations.html#predefined-types-and-classes) and thus already covered by the first item.

2022-03-18 12:03 UTC, henrikt-ma commented
> Technically we don't even really need an item specifically for the base type attributes, since they're declared as parameters in [4.8](https://specification.modelica.org/master/class-predefined-types-and-declarations.html#predefined-types-and-classes) and thus already covered by the first item.

Good point.  I'd be in favor of not over-specifying things, and thus rely completely on other parts of the document.

2022-03-18 13:48 UTC, HansOlsson commented
> OK, let's try to clean up a bit while we're at it. What's the point of having this item at all in the list?
> 
> > \item
> > If \lstinline!v! is a discrete-time component then \lstinline!expr! needs to be a discrete-time expression.

I agree that it follows from the general bindings and considered having it as a (possibly non-normative) sub-item under binding equations giving something like:

- Bindings
   - Parameter-binding
   - Discrete-time
- Perfect matching of equations using variability
- Assignments
   - Multiple return assignment

This corresponds somewhat to the situation in Modelica 3.4 and earlier.

If we instead remove parameter-binding and discrete-time bindings (and view them as obvious) and keep bindings and assignments together then we could have:
- Bindings and assignments
- Multiple return assignment
- Perfect matching of equations

2022-03-21 20:50 UTC, henrikt-ma commented
> If we instead remove parameter-binding and discrete-time bindings (and view them as obvious) and keep bindings and assignments together then we could have:
> 
> * Bindings and assignments
> * Multiple return assignment
> * Perfect matching of equations

Yes, this is how I'd like to do it.  I'll wait another day or so, and if no other opinions are expressed I'll update the PR this way.

2022-03-25 06:50 UTC, henrikt-ma commented
Now the only remaining question, as I see it, is whether we should also do something about #3139.  For example, I think that a new variability rule (placed after the multiple return rule) like the following would fix that issue:
> In a record assignment `r := expr`, the variability of `r` as a structured entity (see section so-and-so) must be at least as variable as `expr`.  This is required also when `expr` is a record constructor expression, unlike record equations where the discrete-valued equation variability rule (see section-so-and-so) may allow record members to be considered separately.

2022-04-12 08:57 UTC, HansOlsson approved these changes
Looks ok now.

2022-04-12 13:33 UTC, henrikt-ma commented
What about the proposal above regarding also fixing #3139 (record assignments)?  Should I add something to this PR so that it can be discussed in a thread of this conversation?

2022-04-12 17:43 UTC, eshmoylova approved these changes

2022-04-12 17:52 UTC, eshmoylova commented
> What about the proposal above regarding also fixing #3139 (record assignments)? Should I add something to this PR so that it can be discussed in a thread of this conversation?

Oops, sorry. I meant to "Quote Reply" but accidentally edited the comment in place. I reverted it the way it was.  And this is my reply:
It would be nice to clarify #3139. But do we have an agreement whether the examples you gave are legal?

2022-04-13 06:04 UTC, henrikt-ma commented
> It would be nice to clarify #3139. But do we have an agreement whether the examples you gave are legal?

I seems like it will take more time to sort out #3139, so let's give up the idea of including a fix in this PR.

2022-04-21 08:21 UTC, merged