Illustrate potential implicit nature of discrete-time Real variable equations
modelica/ModelicaSpecification pull request #3159
Opened 2022-04-27 19:07 UTC by henrikt-ma

This is a follow-up to #3134, where the phone meeting comment https://github.com/modelica/ModelicaSpecification/pull/3134#pullrequestreview-954439113 reflects a decision to avoid scope creep and instead add the examples in a separate PR (this one).

I'm not sure we really need to examples, but lets see where the discussion will take us…

2022-04-28 14:59 UTC, HansOlsson commented on chapters/dae.tex
> +end M;\end{lstlisting}
```suggestion
end M;
\end{lstlisting}
```
The other variant seems too condensed.

2022-04-28 15:20 UTC, HansOlsson commented on chapters/dae.tex
> +    x = 3 * pre(x) - y; // OK, forming nonlinear equation system with y.
```suggestion
\begin{lstlisting}[language=modelica]
model M
  discrete Real x(start = 1.0, fixed = true);
  discrete Real y(start=0.0, fixed=true);
equation
  when sample(1.0, 1.0) then
    y = x ^ 2 + 2 * exp(-time);
    x = 3 * pre(x) - y; // OK, forming nonlinear equation system with y.
```
Will explain in review comment.

2022-04-28 15:22 UTC, HansOlsson requested changes
I would prefer to not add systems of equations between discrete-time variables and variables that are active at other times, since it to me generally indicates a problem with the modeling.
For clocked variables we have made this even stricter.

Note that my proposal is just avoid mentioning it in this PR.

Previously this was also discussed
https://github.com/modelica/ModelicaSpecification/issues/2639

2022-04-28 18:56 UTC, henrikt-ma commented on chapters/dae.tex
> +end M;\end{lstlisting}
Sure, that was a mistake.

2022-04-28 19:07 UTC, henrikt-ma commented
> I would prefer to not add systems of equations between discrete-time variables and variables that are active at other times, since it to me generally indicates a problem with the modeling. For clocked variables we have made this even stricter.
> 
> Note that my proposal is just avoid mentioning it in this PR.

As long as we are all agree that this is a valid example, I'm fine with removing it.  I suggest we bring it up for discussion at the next phone meeting to make sure there is agreement in the group.

2022-05-04 06:41 UTC, HansOlsson commented
> > I would prefer to not add systems of equations between discrete-time variables and variables that are active at other times, since it to me generally indicates a problem with the modeling. For clocked variables we have made this even stricter.
> > Note that my proposal is just avoid mentioning it in this PR.
> 
> As long as we are all agree that this is a valid example, I'm fine with removing it. I suggest we bring it up for discussion at the next phone meeting to make sure there is agreement in the group.

I would prefer to discuss the validity of that separately and for now just add an example without it.

2022-05-12 11:31 UTC, HansOlsson approved these changes
ok

2022-05-12 11:32 UTC, merged