Allow extends from empty base-class and define empty class.
modelica/ModelicaSpecification pull request #3362
Opened 2023-04-05 11:59 UTC by HansOlsson

Closes #3320
As I understand it this corresponds to the decision, but I may have missed something.

2023-04-10 21:29 UTC, henrikt-ma commented on chapters/classes.tex
> +It is not legal to combine equations, algorithms, components, non-empty base classes (see \cref{empty-class}), or protected elements with an extends from an array class, a class with non-empty \lstin
Better to use definition:
```suggestion
It is not legal to combine equations, algorithms, components, non-empty base classes (see below), or protected elements with an extends from an array class, a class with non-empty \lstinline[language=grammar]!base-prefix!, a \firstuse{simple type} (\lstinline!Real!, \lstinline!Boolean!, \lstinline!Integer!, \lstinline!String! and enumeration types), or any class transitively extending from an array class, a class with non-empty \lstinline[language=grammar]!base-prefix!, or a simple type.

\begin{definition}[Empty class]\index{empty-class}
A class without equations, algorithms, or components, and where any base-classes are themselves empty.
\end{definition}

\begin{nonnormative}
An empty class may contain annotations, such as graphics, and can be used more freely as base-class than other classes.
\end{nonnormative}
```

2023-04-10 21:30 UTC, henrikt-ma commented on chapters/classes.tex
> +
Replaced by definition in suggestion above:
```suggestion
```

2023-04-10 21:34 UTC, henrikt-ma commented on chapters/functions.tex
> +  This is the only use of {\lstinline!class!} for a non-empty class, \cref{empty-class}.
This sentence appears incomplete.  Did you mean this?
```suggestion
  Apart from empty classes (\cref{empty-class}), this is the only use of {\lstinline!class!}.
```

2023-04-10 21:40 UTC, henrikt-ma requested changes
In addition to suggestions, I think there are some parts missing:
- the rule for external objects should allow empty base-classes (_An external object class shall… and shall not contain other elements._)
- syntactically allow `extends enumeration(a, b, c);`
- allow combining `extends enumeration(a, b, c);` with extending from empty classes

2023-04-18 15:32 UTC, HansOlsson commented
> the rule for external objects should allow empty base-classes (_An external object class shall… and shall not contain other elements_.)

I have tried to add that.

> syntactically allow `extends enumeration(a, b, c);`

I hadn't thought this was the idea, and to me it looks odd.
The syntactically similar:
```
type E=enumeration(a,b,c);
...
extends E;
```
should work already.

2023-04-19 09:45 UTC, henrikt-ma commented
> > syntactically allow `extends enumeration(a, b, c);`
> 
> I hadn't thought this was the idea, and to me it looks odd.

OK.  It was my interpretation that this was the most desired alternative of the ones discussed in https://github.com/modelica/ModelicaSpecification/issues/3320#issuecomment-1470151361.  I suppose we can seek clarification of this in the next phone meeting.

In the meantime, let's try to work out some details of the alternative solution.  For example, shouldn't we support making the local type protected, so that there is only one public name for the enumeration?
```
package Icons
  type Enum
    annotation(Icon(…));
  end Enum;
end Icons;

type EnumWithIcon
protected
  type T = enumeration(a, b, c);
public
  extends T;
  extends Icons.Enum;  
end EnumWithIcon;

EnumWithIcon e = EnumWithIcon.a;
```

2023-04-21 07:53 UTC, HansOlsson commented
> For example, shouldn't we support making the local type protected, so that there is only one public name for the enumeration?

I'm not sure. I think the current PR works for ExternalObject, and we should have a separate discussion whether more is needed for enumerations and other types.

For enumeration I would say that having a different local name has a benefit - especially as we also have to consider enumeration-connectors that should have different graphics:
```
connector TInput=input T annotation(Icon(graphics...));
connector TOutput=output T annotation(Icon(graphics...));
```
Clearly they should be the same enumeration-type.

However, if we want all enumerations-input-connectors to have a common graphics we would need a local name, and we might also consider if we can have 'input' as part of extends. On the other hand this seems like a lot of complicated grammar with somewhat unclear use-case.

2023-05-04 08:04 UTC, HansOlsson commented
Can we accept this one (which solves the problem for ExternalObject)? And then revisit enumerations. @henrikt-ma

2023-05-04 20:04 UTC, henrikt-ma commented
> Can we accept this one (which solves the problem for ExternalObject)? And then revisit enumerations. @henrikt-ma

Yes, just update the initial comment accordingly so that merging this doesn't trigger the closing action on #3320.

2023-05-12 13:34 UTC, HansOlsson commented
> > Can we accept this one (which solves the problem for ExternalObject)? And then revisit enumerations. @henrikt-ma
> 
> Yes, just update the initial comment accordingly so that merging this doesn't trigger the closing action on #3320.

Done

2023-05-29 20:17 UTC, henrikt-ma commented on chapters/functions.tex
> +  An external object class shall be directly extended from {\lstinline!ExternalObject!}, shall have exactly two function definitions, called {\lstinline!constructor!} and {\lstinline!destructor!}, ma
With one exception (that should also be fixed), we write say _extend from_:
```suggestion
  An external object class shall be directly extended from {\lstinline!ExternalObject!}, shall have exactly two function definitions, called {\lstinline!constructor!} and {\lstinline!destructor!}, may extend from empty classes (\cref{empty-class}), but not contain any other elements.
```

2023-05-29 20:19 UTC, henrikt-ma approved these changes
Just a minar comment about saying _extend from_.  This can be fixed as part of this PR, or together with the other instance of _extend_ without _from_.

2023-05-30 09:50 UTC, merged