Confusion between label and index.
modelica/ModelicaSpecification pull request #3393
Opened 2023-07-06 09:30 UTC by HansOlsson

The empty class definition had an index-entry that was used as label.
Fix that.

2023-07-07 18:24 UTC, henrikt-ma commented on chapters/classes.tex
> +\begin{definition}[Empty class]\index{class!empty}\label{empty-class}
I'd find the direct index entry more useful, doubting that we need one under _class_:
```suggestion
\begin{definition}[Empty class]\index{empty class}\label{empty-class}
```

2023-07-07 18:25 UTC, henrikt-ma requested changes
Good catch. I'd just like to add it to the index differently.

2023-07-12 15:39 UTC, eshmoylova approved these changes

2023-07-16 22:25 UTC, henrikt-ma approved these changes
Looks good.

2023-08-04 14:07 UTC, merged