Separate applying, associating, and inferencing for solverMethod.
modelica/ModelicaSpecification pull request #3479
Opened 2024-02-15 20:40 UTC by HansOlsson

Closes #3465

2024-02-15 20:40 UTC, HansOlsson commented on chapters/synchronous.tex
> +A sub-partition can have an integration method, directly associated \cref{associating-a-solver-to-a-partition} or interferred from other sun-partitions \cref{inferencing-of-solvermethod}.
```suggestion
A sub-partition can have an integration method, directly associated \cref{associating-a-solver-to-a-partition} or interferred from other sub-partitions \cref{inferencing-of-solvermethod}.
```

2024-02-19 15:44 UTC, eshmoylova requested changes
Overall looks good, but a minor typo and punctuation correction.

2024-02-19 15:44 UTC, eshmoylova commented on chapters/synchronous.tex
> +A sub-partition can have an integration method, directly associated \cref{associating-a-solver-to-a-partition} or interferred from other sub-partitions \cref{inferencing-of-solvermethod}.
When compiled, this sentence becomes:
>A sub-partition can have an integration method, directly associated section 16.8.3 or interferred from
other sub-partitions section 16.8.4.

A typo in "inferred" and some punctuation is missing around section 16.8.x. 
```suggestion
A sub-partition can have an integration method, directly associated (\cref{associating-a-solver-to-a-partition}) or inferred from other sub-partitions (\cref{inferencing-of-solvermethod}).
```

2024-02-19 15:55 UTC, eshmoylova approved these changes

2024-02-21 07:40 UTC, merged