Avoid syntax errors.
modelica/ModelicaSpecification pull request #3496
Opened 2024-04-02 11:16 UTC by HansOlsson

Avoid the use of `{}` that isn't described in the grammar.

2024-04-03 06:27 UTC, henrikt-ma requested changes
I find the old way with `{}` much more clear, and it has never been a concern to me that annotations are defined using a style which only reminds of – but isn't exactly – Modelica.

We already have the big discrepancy that there is no built-in record called `Documentation`, and that's not a problem.

I see two better-looking alternatives to `fill("foo", 0)`:
- General use of `{}` rather than `fill("foo", 0)` when defining annotations with defaults.
- General rule that array annotations always default to being empty.

2024-05-31 05:32 UTC, henrikt-ma requested changes
Nothing really changed since my previous review.  More discussion is needed to sort this out.

2025-01-09 13:52 UTC, HansOlsson commented on chapters/annotations.tex
```suggestion
The \lstinline!styleSheets! may also be given as a single string, see \cref{style-sheets}.

```

2025-01-09 13:53 UTC, HansOlsson commented
Since we now define that an array defaults to being empty we can handle it by just removing the default.

2025-01-15 21:28 UTC, henrikt-ma commented on chapters/annotations.tex
> +  /*literal*/ constant String[:] styleSheets  "Style sheets for documentation";
One more space to remove:
```suggestion
  /*literal*/ constant String[:] styleSheets "Style sheets for documentation";
```

2025-01-15 21:28 UTC, henrikt-ma requested changes
Basically good.  Just a tiny whitespace error to fix.

2025-01-18 12:57 UTC, henrikt-ma approved these changes
Looks good.

2025-01-21 16:16 UTC, merged