Simplify text for constraining modifiers
modelica/ModelicaSpecification pull request #3579
Opened 2024-10-01 12:56 UTC by HansOlsson

Don't make a special case for ignoring empty modifiers that don't matter.

Closes #3576

2024-10-02 18:19 UTC, eshmoylova reviewed
I am not 100% sure that the new version says what the old one was trying to say. Let's discuss it in the meeting.

2024-10-03 15:01 UTC, HansOlsson commented
Simplify line before by introducing "original ..." >@hansOlsson

2024-10-03 16:04 UTC, eshmoylova requested changes

2024-10-07 12:07 UTC, eshmoylova approved these changes

2024-10-15 15:01 UTC, merged